artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'C:\Users\Sumant Jagtap\StudioProjects\end-to-end-ml-flow\final_dataset.csv'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion